name: beerproto
description: A implementation of the BeerProto Specification in Dart
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.1
  protobuf: ^4.2.0
  protoc_plugin: ^22.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
